Dev/bj rn/texturefx
vvvv/VL.Stride pull request #387
Opened 2021-01-05 20:14 UTC by bj-rn

Adds a bunch of TextureFX ported from beta (most DX11, a few DX9) and rudimentary "Help Patches".
The patches have no help flag added because of this:
![image](https://user-images.githubusercontent.com/1632591/103690351-80cf0a00-4f8c-11eb-9525-1e26756d664d.png)

There are issues with some of the effects, I think most of them can be attributed to the sRGB "intracacies".

In the beginning I separated  each technique into a single shader/file and then used interfaces for selecting the techniques (did not want to end up with a waterfall as seen in Blend).  Later on I put the techniques inside methods – all in one file – and used a _switch_ statement for selecting them. It is Ia lot less hassle and easier to understand in my opinion, no idea how it impacts performance though.

I am also not quite sure of the categories aka subfolders (_Distortion_, _Math_ etc.) I put the files in.

Below a list of the nodes and some notes I made during "develoment":

### Anaglyph
As far as I can tell the node works as it supposed to, 
But not 100% sure because there is no help patch in beta.
[Source](https://github.com/vvvv/vvvv-sdk/blob/develop/vvvv45/addonpack/lib/nodes/modules/TextureFX/Filter/Anaglyph/Anaglyph.fx)

### BackgroundSubstraction
[Source](https://github.com/vvvv/vvvv-sdk/blob/develop/vvvv45/addonpack/lib/nodes/modules/TextureFX/Filter/BackgroundSubtraction/BackgroundSubtraction.fx)

### Directional Blur
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/BlurDirectional.tfx)

### BlurGlow
Result looks slightly different compared to beta/DX11
![BlurGlow](https://user-images.githubusercontent.com/1632591/103692816-410a2180-4f90-11eb-8bfa-ffe0a6b122fb.png)
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/BlurGlow.tfx)

### BlurPerfector
Results differ from beta/DX11 with same paramters/settings
![BlurPerfector](https://user-images.githubusercontent.com/1632591/103692867-541cf180-4f90-11eb-8a5d-218a99350031.png)
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/BlurPerfector.tfx)

### BubbleNoise
Results are "brighter" than beta/DX11 with same paramters/settings.
![BubbleNoise](https://user-images.githubusercontent.com/1632591/103692899-60a14a00-4f90-11eb-98df-989eb1fac298.png)
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Source/BubbleNoise.tfx)

### Bump
Results differ from beta/DX11 with same paramters/settings.
Maybe due to input from NormalGlow which already differs-
Using an interface for selecting the techniques.
![Bump](https://user-images.githubusercontent.com/1632591/103692989-829acc80-4f90-11eb-8e89-c753c5c5c5d0.png)
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/Bump.tfx)

### ChangeFormat
Module to change textureformat and add mips

### ChannelKey
Keys according to Alpha, Red, Green, Blue, Luma, Saturation.
Was originally called Keying.tfx but since there was already a KeyingBase I named it ChanellKeying
Maybe it should the files should be put into Keying Subdirectory?
The results differ from from beta/DX11, especially when the input texture is Srgb.
Using an interface for selecting the techniques.
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/Keying.tfx)

### Colorize
Results are different compared to beta/DX11, especially if the input texture is sRGB.
![Colorize](https://user-images.githubusercontent.com/1632591/103693197-ce4d7600-4f90-11eb-8d6f-db46cc0b6588.png)
![Colorize_Srgb](https://user-images.githubusercontent.com/1632591/103693221-d86f7480-4f90-11eb-95ea-f1ad91c40941.png)
[Source](https://github.com/vvvv/vvvv-sdk/blob/develop/vvvv45/addonpack/lib/nodes/modules/TextureFX/Filter/Colorize/Colorize.fx)

### ColorMap
Needs first input texture set to RGB and second to sRGB to yield results similar to beta/DX11.
Using an interface for selecting the techniques
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/ColorMap.tfx)

### ColorConvert
Was ConvertColor, decided to rename to be somewhat consistent with ColorMap, ColorRamp.
Results are different (compared to beta/dx11) for: Hue, Saturation, HSVtoRGB and RGBtoHSV
Using an interface for selecting the techniques
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/ConvertColor.tfx)

### CrossStitch
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/CrossStitching.tfx)

### DeInterlace
Not properly tested since there seems to be no way to play interlaced video in gamma currently.
Mediafoundation automagically deinterlaces (but the video stutters).
With OpenCV asImage/toTexture the resulting texture is broken - most likely due to the interlacing.
Help patch is just a placeholder.
[Source](https://discourse.vvvv.org/t/deinterlace-in-opencv-videoin-dx11/14110/9)

### Dissolve
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Mixer/Dissolve.tfx)

### Dither
Results are different compared to beta/dx11.
![Dither](https://user-images.githubusercontent.com/1632591/103693414-297f6880-4f91-11eb-9185-9163350a5866.png)
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/Dither.tfx)

### Dots
Currently PixelSize input is of type int2, maybe make it float2 instead?
[Source](https://github.com/vvvv/vvvv-sdk/blob/develop/vvvv45/addonpack/lib/nodes/modules/TextureFX/Filter/Dots/Dots.fx)

### DropShadow
The results differ from from beta/DX11, especially when the input texture is sRGB.
![DropShadow](https://user-images.githubusercontent.com/1632591/103693476-41ef8300-4f91-11eb-91d3-5b3fed207ba3.png)
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/DropShadow.tfx)

### Edge
Sobel/edge detection
The results differ from from beta/DX11
![Edge](https://user-images.githubusercontent.com/1632591/103693507-503d9f00-4f91-11eb-97fd-18bbe39c5b2b.png)
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/Edge.tfx)

### Electricity
Isn't working even though there are no errors. I guess either the volume texture isn't loaded correctly
or only one slice is accessible inside the shader.
![Electricity](https://user-images.githubusercontent.com/1632591/103693548-60ee1500-4f91-11eb-8985-d7ac92cc9dc7.png)
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Source/Electricity.tfx)

### Halo
The results differ from from beta/DX11. Maybe due to the different texture format?
DX11 uses R16G16B16A16_Float which is not available in Stride. 
Uses Switch statement for different "Techniques".
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Source/Halo.tfx)

### Hatch (Cross)
Results differ slightly when input texture is RGB and there is a big difference when using a sRGB texture as input.
Maybe could be combined with Hatch (Dot), Hatch (FromTexture) and Hatch (Line). 
![HatchCross](https://user-images.githubusercontent.com/1632591/103693628-867b1e80-4f91-11eb-9b3b-1276da7e857d.png)
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/HatchCrossed.tfx)

### Hatch (Dot)
Results differ slightly when input texture is RGB and there is a big difference when using a sRGB texture as input.
Maybe could be combined with Hatch (Cross), Hatch (FromTexture) and Hatch (Line). 
[Source](https://github.com/mrvux/dx11-vvvv-girlpower/blob/master/nodes/texture11/Filter/HatchDot.tfx)

### Hatch (FromTexture)
Maybe could be combined with Hatch (Dot), Hatch (Cross) and Hatch (Line). 
[Source](https://github.com/vvvv/vvvv-sdk/blob/develop/vvvv45/addonpack/lib/nodes/modules/TextureFX/Filter/HatchFromTexture/HatchFromTexture.fx)

### Hatch (Line)
Maybe could be combined with Hatch (Dot), Hatch (Cross) and Hatch (FromTexture). 
Has its own implementation of r2d which differs from the o [...]

2021-01-06 19:55 UTC, azeno requested changes
Wow, big one. Thanks for the great work!

I left a few comments in the code itself. Mostly about readability. Most of the shaders also have formatting issues, would be nice to fix them first. At a lot of places it's also hard to understand what's going on due to missing comments and explanations. But I guess that's because the code was copied over and the original had no comments either?

Because the PR is so huge, I'd vote for accepting it and see what issues come up over time.

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Sources/Palette_TextureFX.sdsl
> +        col.rgb = float3(uv.x, uv.y, length(uv));
This line can be removed, value gets overwritten in next line.

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Sources/Palette_TextureFX.sdsl
> +        uv = mul(float4((uv.xy*2-1)*float2(1,-1)*.5,0,1), Transform).xy*float2(1,-1) + 0.5;
This line can be seen quite often. Would probably be nice to extract into a function.

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Sources/Palette_TextureFX.sdsl
> +        float2 R = 1/Texture0TexelSize;
Not used?

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/Patterns/CrossStitch_TextureFX.sdsl
> +                col = Texture0.SampleLevel(LinearRepeatSampler, tlPos * float2(1.0/R.x, 1.0/R.y), 0) * 1.4;
Instead of float2(1/R) simply use Texture0TexelSize

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/DropShadow_TextureFX.sdsl
> +        float lod = log2(max(R.x, R.y));
Remove this line - already covered by next line

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/DropShadow_TextureFX.sdsl
> +        float2 off = .5/R*pow(2,lod) * saturate(lod);
Hm, again 0.5/R = 0.5/(1/Texture0TexelSize) = 0.5 * TexelSize - would be easier to read.
In general not sure about the saturate(lod), isn't that always just 1? lod is based on the log of the texture dimensions, so it's safe to assume to always be > 1, meaning saturate (which clamps between 0 and 1) will simply return 1. Would be nice to have some comments here ..

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Edge_TextureFX.sdsl
> +		return Texture0.SampleLevel(LinearSampler, uv + off/R, v);
The parameter R could be removed, see below.

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Edge_TextureFX.sdsl
> +    	float3 e = float3(1, -1, 0) * rad;
Multiply with TexelSize and we can get rid of the R parameter.

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Edge_TextureFX.sdsl
> +		float4 col = sqrt(cx*cx+cy*cy) * Bright * pow(2, rad/max(R.x, R.y))/sqrt(saturate(rad) + .001);
Again, simpler would be rad * max(TexelSize.x, ...)

2021-01-06 19:55 UTC, azeno commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/TextureFXTechniqueEnums.cs
> +    public enum PaletteTechnique { HSL, HSV, Radial };
The help patch of the Palette node makes use of this enum, however the node doesn't have it anymore, uses an integer instead. Is this an oversight? I didn't check the other enums.

2021-01-06 20:03 UTC, azeno commented
That the examples look different compared to beta is understandable due to the linear color space. We have a help patch which shows how to switch the device to the Gamma color space, pasting the examples in there and things looks the same as in beta.

Reasoning what looks more correct is a little hard I must admit. For example the blur examples look different because of the generated mip maps. On the poles the level 6 mip map is a little brighter in Linear than in Gamma. Probably because of the filtering when downscaling it (averaging color values).

The edge examples look more correct to me - the colors get preserved, in Gamma space it all turns dark. But not sure whether or not that was the intention.

The palette example puzzles me. I read in some other thread that color palettes look different when generated in Linear space and that's how it's supposed to be. Or in other words in doesn't look linear on the eye, while it looked linear when it was created in Gamma space. So I wonder whether in such a case we must return with `ColorUtility.ToLinear(col)` - but then one immediately wonders where else that must be done. Little clueless here. 
Good articles about this whole topic are https://medium.com/game-dev-daily/the-srgb-learning-curve-773b7f68cf7a and https://developer.nvidia.com/gpugems/gpugems3/part-iv-image-effects/chapter-24-importance-being-linear however after reading them three times now over the last couple of months I'm sometimes still puzzled. Especially when "comparing" results of "older" programs.

2021-01-06 23:50 UTC, bj-rn commented
> Wow, big one. Thanks for the great work!
> I left a few comments in the code itself. Mostly about readability. Most of the shaders also have formatting issues, would be nice to fix them first. 

You mean the indentations? This didn't show up locally. I copied the code out of the beta code editor and used VS Code and VS to edit. Just cloned it here at home and looking at it now, the editors must have had different settings for indentations, tabs / spaces ... Will fix this tomorrow at the office -  using spaces.
![image](https://user-images.githubusercontent.com/1632591/103832483-48a3f600-5076-11eb-84a9-86bf3b908496.png)

>At a lot of places it's also hard to understand what's going on due to missing comments and explanations. But I guess that's because the code was copied over and the original had no comments either?

Exactly. Some of it looked pretty freestyle to me and to be honest most of the time I didn't go through the code line by line trying to understand everything, much less trying to improve it. So for example when Targetsize was used I just added `float2 R = 1/Texture0TexelSize; `  Will go through your comments and try to fix those.

>Reasoning what looks more correct is a little hard I must admit.

Same here, I don't know and wouldn't know how to make it right either way :)

2021-01-07 10:01 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Sources/Palette_TextureFX.sdsl
> +        uv = mul(float4((uv.xy*2-1)*float2(1,-1)*.5,0,1), Transform).xy*float2(1,-1) + 0.5;
How would you call it? 
And then put in in _Effects/Common/ShaderUtils.sdsl_ ,I guess. But there is also _Effects/Common/Utils.sdsl_ which seems outdated.

2021-01-07 11:01 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Colorize_TextureFX.sdsl
> +        float4 pixcol = length(Texture0.Sample(LinearSampler, uv).rgb);
https://github.com/bj-rn/VL.Stride/commit/61f84c9af1b6d7d7781ea82bad1eabc63e4d34a9

2021-01-07 11:02 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Colorize_TextureFX.sdsl
> +        float lum = (pixcol.r+pixcol.g+pixcol.b)/3.0;
https://github.com/bj-rn/VL.Stride/commit/61f84c9af1b6d7d7781ea82bad1eabc63e4d34a9

2021-01-07 11:02 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Colorize_TextureFX.sdsl
> +        tc = lerp(colors[ix], colors[ix+1], (lum - float(ix)*0.5)/0.5);
https://github.com/bj-rn/VL.Stride/commit/61f84c9af1b6d7d7781ea82bad1eabc63e4d34a9

2021-01-07 11:02 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Colorize_TextureFX.sdsl
> +        return float4(tc, pixcol.a);
Don't remember ... https://github.com/bj-rn/VL.Stride/commit/61f84c9af1b6d7d7781ea82bad1eabc63e4d34a9

2021-01-07 11:03 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Sources/Palette_TextureFX.sdsl
> +        col.rgb = float3(uv.x, uv.y, length(uv));
https://github.com/bj-rn/VL.Stride/commit/f13229106b38266b9b286e9d3446c07274d53f9e

2021-01-07 11:03 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Sources/Palette_TextureFX.sdsl
> +        uv = mul(float4((uv.xy*2-1)*float2(1,-1)*.5,0,1), Transform).xy*float2(1,-1) + 0.5;
https://github.com/bj-rn/VL.Stride/commit/f13229106b38266b9b286e9d3446c07274d53f9e

2021-01-07 11:03 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Sources/Palette_TextureFX.sdsl
> +        float2 R = 1/Texture0TexelSize;
https://github.com/bj-rn/VL.Stride/commit/f13229106b38266b9b286e9d3446c07274d53f9e

2021-01-07 11:03 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/Patterns/CrossStitch_TextureFX.sdsl
> +                col = Texture0.SampleLevel(LinearRepeatSampler, tlPos * float2(1.0/R.x, 1.0/R.y), 0) * 1.4;
https://github.com/bj-rn/VL.Stride/commit/8b002680e7f069e8092338e526c883ffa246348d

2021-01-07 11:04 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/DropShadow_TextureFX.sdsl
> +        float lod = log2(max(R.x, R.y));
https://github.com/bj-rn/VL.Stride/commit/2dfd9a6e4d71afe719d950c6173c72eb692f71d4

2021-01-07 11:04 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Edge_TextureFX.sdsl
> +		return Texture0.SampleLevel(LinearSampler, uv + off/R, v);
https://github.com/bj-rn/VL.Stride/commit/9542ce7eea3475d4b082528a7b1b2500e40f73b7

2021-01-07 11:05 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Edge_TextureFX.sdsl
> +    	float3 e = float3(1, -1, 0) * rad;
https://github.com/bj-rn/VL.Stride/commit/9542ce7eea3475d4b082528a7b1b2500e40f73b7

2021-01-07 11:05 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/Edge_TextureFX.sdsl
> +		float4 col = sqrt(cx*cx+cy*cy) * Bright * pow(2, rad/max(R.x, R.y))/sqrt(saturate(rad) + .001);
https://github.com/bj-rn/VL.Stride/commit/9542ce7eea3475d4b082528a7b1b2500e40f73b7

2021-01-07 11:06 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/TextureFXTechniqueEnums.cs
> +    public enum PaletteTechnique { HSL, HSV, Radial };
This was an oversight seems I forgot to save VL.Stride.Rendering.TextureFX.vl
https://github.com/bj-rn/VL.Stride/commit/c55b613b1704e92dc70706e2b503f273ec5a23e7

2021-01-07 11:41 UTC, bj-rn commented on packages/VL.Stride.Runtime/src/Effects/TextureFX/Filters/ColorManipulation/DropShadow_TextureFX.sdsl
> +        float2 off = .5/R*pow(2,lod) * saturate(lod);
Changed the line accordingly: https://github.com/bj-rn/VL.Stride/commit/5c3756b31801ad6e18c10c602efffbd21f6d4b56.
Unfortunately I lack the knowlegde to answer your question.

2021-01-08 16:18 UTC, azeno approved these changes
Ok thanks, I'll merge this PR now so it's part of the next release. I guess the issues will pop-up once we all start using the nodes. 

In the future it would be nice to initiate such a huge PR right at the moment when beginning working on it (marking the PR as a draft), so we all see the progress and can give hints and suggestions early on.

2021-01-08 16:18 UTC, merged

2021-01-08 16:33 UTC, bj-rn commented
> Ok thanks, I'll merge this PR now so it's part of the next release. I guess the issues will pop-up once we all start using the nodes.
> 
> In the future it would be nice to initiate such a huge PR right at the moment when beginning working on it (marking the PR as a draft), so we all see the progress and can give hints and suggestions early on.

I didn't know it would turn out like this. I was bored during the holidays/isolation and started to port some effects planning to post them in the wip forum, then my ocd took over.

2021-01-09 14:02 UTC, tebjan commented
I'd revert the merge until we discussed it internally. I think we should properly evaluate the consequences and identify what needs to be done now and what can be done later.

So please wait a bit before we have more clarity about the involved issues.

2021-01-10 18:02 UTC, azeno commented
Ok just recognized that we have a node name clash as well (ColorMap), turning many help patches red. Reminds me that we (as was done in Stride lately) need to setup TeamCity so it also builds and runs tests of pull requests.

Some nodes also don't dispose the internal state properly (like ColorMap). The internally used interface (like `IColorMap`) should inherit from `IDisposable` which should be called by the wrapper node on its own `Dispose`. This can be quite problematic as it leaves the game per entry point open and things don't properly shutdown on F8 or app close.

@bj-rn sorry for that, I'll revert the merge of this PR and would kindly ask you to open a new one as there's no way to re-open this one. Then @tebjan can also add his comments and we can discuss the naming conflicts as well as the dispose issues.

2021-03-13 11:03 UTC, cloneproduction commented
Hi, cool stuff here. Seems like most of the TFX are about to be ported. Just tried VL a bit and I found that Blend Texture is missing and here also. @bj-rn  are you planning to port that one too ?

2021-03-13 11:52 UTC, bj-rn commented
Hello,
Blend is already available in Stride:
![image](https://user-images.githubusercontent.com/1632591/111028895-a1cf3380-83f1-11eb-90d1-16554264f649.png)

btw this pull request has been closed and reopned as https://github.com/vvvv/VL.Stride/pull/393 
The FX are / will be separated into : core, practical and gimmick. See: https://github.com/vvvv/VL.Stride/pull/393#issuecomment-758811569
Not not sure about the current state of affairs but afaik @tebjan is currently adding [the core part](https://github.com/vvvv/VL.Stride/pull/395)

2021-03-23 04:12 UTC, cloneproduction commented
Strange I can't find that node but there is "BloodShader" which seems to be a textureFX. I'm using a fresh install by the way.

2021-03-25 09:36 UTC, cloneproduction commented
Found it. Had to toggle experimental nodes in nodebrowser.